import type { ItemDefinition } from "./itemTypes";

export const foodItemsData: ItemDefinition[] = [
  {
    key: "fish",
    name: "River Fish",
    iconKey: "fish",
    weight: 0.8,
    description: "A small river catch. Better cooked than eaten raw.",
    stats: ["Food item"],
    category: "food",
    stackable: true,
    baseValue: 3,
    tags: ["food", "survival"],
  },
  {
    key: "cookie",
    name: "Cookie",
    iconKey: "ration",
    weight: 0.1,
    description: "A hard travel biscuit that somehow survived the damp.",
    stats: ["Food item"],
    category: "food",
    stackable: true,
    baseValue: 2,
    tags: ["food", "travel"],
  },
  {
    key: "fruit",
    name: "Wild Fruit",
    iconKey: "fruit",
    weight: 0.2,
    description: "A handful of fruit gathered from the old rural outskirts.",
    stats: ["Natural good"],
    category: "food",
    stackable: true,
    baseValue: 2,
    tags: ["food", "foraging"],
  },
  {
    key: "rabbit-meat",
    name: "Rabbit Meat",
    iconKey: "meat",
    weight: 0.6,
    description: "Freshly hunted small game from the hills and brush.",
    stats: ["Food item"],
    category: "food",
    stackable: true,
    baseValue: 4,
    tags: ["food", "hunting"],
  },
];
