import type { ItemDefinition } from "./itemTypes";

export const materialItemsData: ItemDefinition[] = [
  {
    key: "stone",
    name: "Stone",
    icon: "ðŸª¨",
    weight: 1.5,
    description: "A rough stone used for crafting and construction.",
    stats: ["Crafting material"],
    category: "material",
    stackable: true,
    baseValue: 1,
    tags: ["material", "construction"],
  },
  {
    key: "herb",
    name: "Herb",
    icon: "ðŸŒ¿",
    weight: 0.2,
    description: "A medicinal herb with basic healing properties.",
    stats: ["Consumable ingredient"],
    category: "material",
    stackable: true,
    baseValue: 2,
    tags: ["material", "alchemy"],
  },
  {
    key: "wood",
    name: "Wood",
    icon: "ðŸªµ",
    weight: 2.0,
    description: "Dry timber used for fuel, tools, and structures.",
    stats: ["Crafting material"],
    category: "material",
    stackable: true,
    baseValue: 1,
    tags: ["material", "construction"],
  },
  {
    key: "rope",
    name: "Rope",
    icon: "ðŸª¢",
    weight: 1.0,
    description: "Useful for climbing, binding, and field repairs.",
    stats: ["Traversal utility"],
    category: "material",
    stackable: true,
    baseValue: 4,
    tags: ["material", "utility", "traversal"],
  },
  {
    key: "paper",
    name: "Paper Scrap",
    icon: "ðŸ“œ",
    weight: 0.1,
    description: "A fragile sheet salvaged from old records and books.",
    stats: ["Quest item material"],
    category: "quest",
    stackable: true,
    baseValue: 1,
    tags: ["quest", "lore", "material"],
  },
];
