"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getAllCreatureSpeciesMasterData = exports.getCreatureSpeciesMasterData = exports.getCreatureSpeciesSnapshot = exports.creatureSpeciesData = void 0;
var creatureSpeciesData_1 = require("./domain/creatureSpeciesData");
Object.defineProperty(exports, "creatureSpeciesData", { enumerable: true, get: function () { return creatureSpeciesData_1.creatureSpeciesData; } });
var getCreatureSpeciesSnapshot_1 = require("./application/selectors/getCreatureSpeciesSnapshot");
Object.defineProperty(exports, "getCreatureSpeciesSnapshot", { enumerable: true, get: function () { return getCreatureSpeciesSnapshot_1.getCreatureSpeciesSnapshot; } });
var creatureSpeciesMasterDataAdapter_1 = require("./infrastructure/creatureSpeciesMasterDataAdapter");
Object.defineProperty(exports, "getCreatureSpeciesMasterData", { enumerable: true, get: function () { return creatureSpeciesMasterDataAdapter_1.getCreatureSpeciesMasterData; } });
Object.defineProperty(exports, "getAllCreatureSpeciesMasterData", { enumerable: true, get: function () { return creatureSpeciesMasterDataAdapter_1.getAllCreatureSpeciesMasterData; } });
