import healthPotionImage from "../../../assets/items/potions/healthpotion.png";
import manaPotionImage from "../../../assets/items/potions/manapotion.png";
import staminaPotionImage from "../../../assets/items/potions/staminapotion.png";
import attackImage from "../../../assets/sprites/hud/attack.png";
import dodgeImage from "../../../assets/sprites/hud/dodge.png";
import type {
  CombatActionDefinition,
  CombatActionId,
  CombatInputBinding,
} from "./combatEngineTypes";

export const combatActionCatalog: Record<CombatActionId, CombatActionDefinition> = {
  "basic-attack": {
    id: "basic-attack",
    type: "basic-attack",
    label: "Attack",
    description: "Strike the current enemy with a basic weapon attack.",
    hotkey: "Space",
    consumesAction: true,
    iconKey: "attack",
    iconImageSrc: attackImage,
    fallbackIcon: "⚔",
  },
  "use-life-potion": {
    id: "use-life-potion",
    type: "use-potion",
    label: "Life Potion",
    description: "Restore health with the equipped life potion.",
    hotkey: "1",
    consumesAction: true,
    iconKey: "life-potion",
    iconImageSrc: healthPotionImage,
    fallbackIcon: "🧪",
    potionItemKey: "life-potion",
    potionResource: "hp",
  },
  "use-mana-potion": {
    id: "use-mana-potion",
    type: "use-potion",
    label: "Mana Potion",
    description: "Restore spiritual power with the equipped mana potion.",
    hotkey: "2",
    consumesAction: true,
    iconKey: "mana-potion",
    iconImageSrc: manaPotionImage,
    fallbackIcon: "🧴",
    potionItemKey: "mana-potion",
    potionResource: "sp",
  },
  "use-variable-potion": {
    id: "use-variable-potion",
    type: "use-potion",
    label: "Variable Potion",
    description: "Recover both HP and SP with the hybrid potion.",
    hotkey: "3",
    consumesAction: true,
    iconKey: "variable-potion",
    iconImageSrc: staminaPotionImage,
    fallbackIcon: "⚗",
    potionItemKey: "variable-potion",
    potionResource: "hybrid",
  },
  dodge: {
    id: "dodge",
    type: "dodge",
    label: "Dodge",
    description: "Prepare an evasive response against the next incoming strike.",
    hotkey: "Ctrl",
    consumesAction: true,
    iconKey: "dodge",
    iconImageSrc: dodgeImage,
    fallbackIcon: "🜂",
  },
  "skill-slot-1": {
    id: "skill-slot-1",
    type: "skill",
    label: "Skill 1",
    description: "Empty combat skill slot.",
    hotkey: "Q",
    consumesAction: false,
    iconKey: "skill-slot-1",
    fallbackIcon: "✦",
    skillSlot: 1,
  },
  "skill-slot-2": {
    id: "skill-slot-2",
    type: "skill",
    label: "Skill 2",
    description: "Empty combat skill slot.",
    hotkey: "W",
    consumesAction: false,
    iconKey: "skill-slot-2",
    fallbackIcon: "✦",
    skillSlot: 2,
  },
  "skill-slot-3": {
    id: "skill-slot-3",
    type: "skill",
    label: "Skill 3",
    description: "Empty combat skill slot.",
    hotkey: "E",
    consumesAction: false,
    iconKey: "skill-slot-3",
    fallbackIcon: "✦",
    skillSlot: 3,
  },
  "skill-slot-4": {
    id: "skill-slot-4",
    type: "skill",
    label: "Skill 4",
    description: "Empty combat skill slot.",
    hotkey: "A",
    consumesAction: false,
    iconKey: "skill-slot-4",
    fallbackIcon: "✦",
    skillSlot: 4,
  },
  "skill-slot-5": {
    id: "skill-slot-5",
    type: "skill",
    label: "Skill 5",
    description: "Empty combat skill slot.",
    hotkey: "S",
    consumesAction: false,
    iconKey: "skill-slot-5",
    fallbackIcon: "✦",
    skillSlot: 5,
  },
  "skill-slot-6": {
    id: "skill-slot-6",
    type: "skill",
    label: "Skill 6",
    description: "Empty combat skill slot.",
    hotkey: "D",
    consumesAction: false,
    iconKey: "skill-slot-6",
    fallbackIcon: "✦",
    skillSlot: 6,
  },
  "skill-slot-7": {
    id: "skill-slot-7",
    type: "skill",
    label: "Skill 7",
    description: "Empty combat skill slot.",
    hotkey: "Z",
    consumesAction: false,
    iconKey: "skill-slot-7",
    fallbackIcon: "✦",
    skillSlot: 7,
  },
  "skill-slot-8": {
    id: "skill-slot-8",
    type: "skill",
    label: "Skill 8",
    description: "Empty combat skill slot.",
    hotkey: "X",
    consumesAction: false,
    iconKey: "skill-slot-8",
    fallbackIcon: "✦",
    skillSlot: 8,
  },
  "skill-slot-9": {
    id: "skill-slot-9",
    type: "skill",
    label: "Skill 9",
    description: "Empty combat skill slot.",
    hotkey: "C",
    consumesAction: false,
    iconKey: "skill-slot-9",
    fallbackIcon: "✦",
    skillSlot: 9,
  },
};

export const combatInputBindings: CombatInputBinding[] = [
  { key: "1", actionId: "use-life-potion" },
  { key: "2", actionId: "use-mana-potion" },
  { key: "3", actionId: "use-variable-potion" },
  { key: "q", actionId: "skill-slot-1" },
  { key: "w", actionId: "skill-slot-2" },
  { key: "e", actionId: "skill-slot-3" },
  { key: "a", actionId: "skill-slot-4" },
  { key: "s", actionId: "skill-slot-5" },
  { key: "d", actionId: "skill-slot-6" },
  { key: "z", actionId: "skill-slot-7" },
  { key: "x", actionId: "skill-slot-8" },
  { key: "c", actionId: "skill-slot-9" },
  { key: " ", actionId: "basic-attack" },
  { key: "control", actionId: "dodge" },
];

export const combatActionBarOrder: CombatActionId[] = [
  "basic-attack",
  "dodge",
  "use-life-potion",
  "use-mana-potion",
  "use-variable-potion",
  "skill-slot-1",
  "skill-slot-2",
  "skill-slot-3",
  "skill-slot-4",
  "skill-slot-5",
  "skill-slot-6",
  "skill-slot-7",
  "skill-slot-8",
  "skill-slot-9",
];
