import type {
  CombatActionDefinition,
  CombatActionId,
  CombatInputBinding,
} from "./combatEngineTypes";

export const combatActionCatalog: Record<CombatActionId, CombatActionDefinition> = {
  "basic-attack": {
    id: "basic-attack",
    type: "basic-attack",
    label: "Attack",
    hotkey: "Space",
    consumesAction: true,
  },
  "use-life-potion": {
    id: "use-life-potion",
    type: "use-potion",
    label: "Life Potion",
    hotkey: "1",
    consumesAction: true,
    potionItemKey: "life-potion",
    potionResource: "hp",
  },
  "use-mana-potion": {
    id: "use-mana-potion",
    type: "use-potion",
    label: "Mana Potion",
    hotkey: "2",
    consumesAction: true,
    potionItemKey: "mana-potion",
    potionResource: "sp",
  },
  "use-variable-potion": {
    id: "use-variable-potion",
    type: "use-potion",
    label: "Variable Potion",
    hotkey: "3",
    consumesAction: true,
    potionItemKey: "variable-potion",
    potionResource: "hybrid",
  },
  dodge: {
    id: "dodge",
    type: "dodge",
    label: "Dodge",
    hotkey: "Ctrl",
    consumesAction: true,
  },
  "skill-slot-1": {
    id: "skill-slot-1",
    type: "skill",
    label: "Skill 1",
    hotkey: "Q",
    consumesAction: false,
    skillSlot: 1,
  },
  "skill-slot-2": {
    id: "skill-slot-2",
    type: "skill",
    label: "Skill 2",
    hotkey: "W",
    consumesAction: false,
    skillSlot: 2,
  },
  "skill-slot-3": {
    id: "skill-slot-3",
    type: "skill",
    label: "Skill 3",
    hotkey: "E",
    consumesAction: false,
    skillSlot: 3,
  },
  "skill-slot-4": {
    id: "skill-slot-4",
    type: "skill",
    label: "Skill 4",
    hotkey: "A",
    consumesAction: false,
    skillSlot: 4,
  },
  "skill-slot-5": {
    id: "skill-slot-5",
    type: "skill",
    label: "Skill 5",
    hotkey: "S",
    consumesAction: false,
    skillSlot: 5,
  },
  "skill-slot-6": {
    id: "skill-slot-6",
    type: "skill",
    label: "Skill 6",
    hotkey: "D",
    consumesAction: false,
    skillSlot: 6,
  },
  "skill-slot-7": {
    id: "skill-slot-7",
    type: "skill",
    label: "Skill 7",
    hotkey: "Z",
    consumesAction: false,
    skillSlot: 7,
  },
  "skill-slot-8": {
    id: "skill-slot-8",
    type: "skill",
    label: "Skill 8",
    hotkey: "X",
    consumesAction: false,
    skillSlot: 8,
  },
  "skill-slot-9": {
    id: "skill-slot-9",
    type: "skill",
    label: "Skill 9",
    hotkey: "C",
    consumesAction: false,
    skillSlot: 9,
  },
};

export const combatInputBindings: CombatInputBinding[] = [
  { key: "1", actionId: "use-life-potion" },
  { key: "2", actionId: "use-mana-potion" },
  { key: "3", actionId: "use-variable-potion" },
  { key: "q", actionId: "skill-slot-1" },
  { key: "w", actionId: "skill-slot-2" },
  { key: "e", actionId: "skill-slot-3" },
  { key: "a", actionId: "skill-slot-4" },
  { key: "s", actionId: "skill-slot-5" },
  { key: "d", actionId: "skill-slot-6" },
  { key: "z", actionId: "skill-slot-7" },
  { key: "x", actionId: "skill-slot-8" },
  { key: "c", actionId: "skill-slot-9" },
  { key: " ", actionId: "basic-attack" },
  { key: "control", actionId: "dodge" },
];

export const combatActionBarOrder: CombatActionId[] = [
  "basic-attack",
  "dodge",
  "use-life-potion",
  "use-mana-potion",
  "use-variable-potion",
  "skill-slot-1",
  "skill-slot-2",
  "skill-slot-3",
  "skill-slot-4",
  "skill-slot-5",
  "skill-slot-6",
  "skill-slot-7",
  "skill-slot-8",
  "skill-slot-9",
];
