import { averonContinentArt, belagardContinentArt, borgeBridgeContinentArt, desertOfPagosContinentArt, edorasContinentArt, fettisStrongholdContinentArt, firstWatchContinentArt, foulBogContinentArt, hellosContinentArt, ironCathedralContinentArt, oldBasaltMineContinentArt, praeriesContinentArt, peregrineShipwreckContinentArt, resistanceContinentArt, sunkenRestContinentArt, thousandIslandsContinentArt, vaultwaysContinentArt, } from "../../../assets/world/continent-maps";
export const worldMapImageDimensions = {
    width: 1536,
    height: 1024,
};
export const worldMapPoisData = [
    {
        id: "old-basalt-mine",
        label: "Old Basalt Mine",
        position: { xPercent: 23.2, yPercent: 75.1 },
        description: "An ancient excavation tunneled into the eastern mountains, prepared as a future travel and underground interaction point.",
        illustration: oldBasaltMineContinentArt,
        linkedMapIds: ["old-basalt-mine"],
        supportsFastTravel: true,
    },
    {
        id: "belagard",
        label: "Belegard",
        position: { xPercent: 13.8, yPercent: 63 },
        description: "A central inland settlement route, currently acting as the closest continent-level anchor for Belegard's local prototype region.",
        illustration: belagardContinentArt,
        linkedMapIds: ["belagard", "town", "sewer", "north-forest", "southwest-farm"],
        supportsFastTravel: true,
    },
    {
        id: "foul-bog",
        label: "Foul Bog",
        position: { xPercent: 27.8, yPercent: 47.1 },
        description: "A marsh-heavy frontier known for stagnant water, hidden trails, and future discovery-based travel hooks.",
        illustration: foulBogContinentArt,
        linkedMapIds: ["foul-bog"],
        supportsFastTravel: true,
    },
    {
        id: "averon",
        label: "Averon",
        position: { xPercent: 16.4, yPercent: 44.7 },
        description: "A western ruin-site and regional anchor on the continent map, prepared for future interaction and travel connections.",
        illustration: averonContinentArt,
        linkedMapIds: ["averon"],
        supportsFastTravel: true,
    },
    {
        id: "peregrine-shipwreck",
        label: "The Peregrine Shipwreck",
        position: { xPercent: 21.8, yPercent: 22.4 },
        description: "A wreck on the southwestern coast, suitable for future exploration rewards, quests, or transport routes.",
        illustration: peregrineShipwreckContinentArt,
        linkedMapIds: ["peregrine-shipwreck"],
        supportsFastTravel: true,
    },
    {
        id: "edoras",
        label: "Edoras",
        position: { xPercent: 40.4, yPercent: 35.6 },
        description: "A southern stronghold nested between forest and water, reserved for future regional routing and discoveries.",
        illustration: edorasContinentArt,
        linkedMapIds: ["edoras"],
        supportsFastTravel: true,
    },
    {
        id: "thousand-islands",
        label: "Thousand Islands",
        position: { xPercent: 56.7, yPercent: 21.5 },
        description: "A wide northern archipelago that can later support sea travel, exploration chains, and distant world progression.",
        illustration: thousandIslandsContinentArt,
        linkedMapIds: ["thousand-islands"],
        supportsFastTravel: true,
    },
    {
        id: "first-watch",
        label: "First Watch",
        position: { xPercent: 44.2, yPercent: 50.1 },
        description: "An old western lookout and future macro-route checkpoint across the swamp frontier.",
        illustration: firstWatchContinentArt,
        linkedMapIds: ["first-watch"],
        supportsFastTravel: true,
    },
    {
        id: "hellos",
        label: "Hellos",
        position: { xPercent: 38.7, yPercent: 66.3 },
        description: "A distant southern landing on the continent map, prepared for later route expansion.",
        illustration: hellosContinentArt,
        linkedMapIds: ["hellos"],
        supportsFastTravel: true,
    },
    {
        id: "borge-bridge",
        label: "Borge Bridge",
        position: { xPercent: 50.1, yPercent: 40.0 },
        description: "The great bridge between the western and eastern landmasses, ideal for future travel validation and route gating.",
        illustration: borgeBridgeContinentArt,
        linkedMapIds: ["borge-bridge"],
        supportsFastTravel: true,
    },
    {
        id: "iron-cathedral",
        label: "Iron Cathedral",
        position: { xPercent: 68.6, yPercent: 39.5 },
        description: "A landmark embedded in the eastern heights, prepared as a future lore and travel destination.",
        illustration: ironCathedralContinentArt,
        linkedMapIds: ["iron-cathedral"],
        supportsFastTravel: true,
    },
    {
        id: "desert-of-pagos",
        label: "Desert of Pagos",
        position: { xPercent: 73.9, yPercent: 55.1 },
        description: "The great southeastern desert, already useful as a continent-level destination and future travel zone.",
        illustration: desertOfPagosContinentArt,
        linkedMapIds: ["desert-of-pagos"],
        supportsFastTravel: true,
    },
    {
        id: "sunken-rest",
        label: "Sunken Rest",
        position: { xPercent: 74.5, yPercent: 73.8 },
        description: "A drowned inlet or ruin-zone in the southeast, reserved for future exploration and navigation hooks.",
        illustration: sunkenRestContinentArt,
        linkedMapIds: ["sunken-rest"],
        supportsFastTravel: true,
    },
    {
        id: "resistance",
        label: "Resistance",
        position: { xPercent: 80.3, yPercent: 64.2 },
        description: "A hardened southern outpost in the desert frontier, suitable for future faction, quest, or travel use.",
        illustration: resistanceContinentArt,
        linkedMapIds: ["resistance"],
        supportsFastTravel: true,
    },
    {
        id: "praeries",
        label: "Praeries",
        position: { xPercent: 84.5, yPercent: 49.7 },
        description: "The open southern plains and farmland belt, currently the closest continent-level match for the Southwest Farm region.",
        illustration: praeriesContinentArt,
        linkedMapIds: ["praeries"],
        supportsFastTravel: true,
    },
    {
        id: "vaultways",
        label: "Vaultways",
        position: { xPercent: 92.6, yPercent: 35.1 },
        description: "A mountain-carved passage system and likely future underground transition network.",
        illustration: vaultwaysContinentArt,
        linkedMapIds: ["vaultways"],
        supportsFastTravel: true,
    },
    {
        id: "fettis-stronghold",
        label: "Fetti's Stronghold",
        position: { xPercent: 88.7, yPercent: 19.9 },
        description: "A northern-eastern mountain fortress that can later serve as a high-level regional destination.",
        illustration: fettisStrongholdContinentArt,
        linkedMapIds: ["fettis-stronghold"],
        supportsFastTravel: true,
    },
];
