export const talentTreesData = [
    {
        key: "wasteland-survivor",
        label: "Wasteland Survivor",
        description: "Life skills, field utility, crafting, and harsh-environment adaptation.",
        nodes: [
            {
                key: "survivor-fishing-instinct",
                archetypeKey: "wasteland-survivor",
                title: "Fishing Instinct",
                description: "Improves your confidence around survival-focused resource loops.",
                unlockLevel: 5,
                gridColumn: 1,
                gridRow: 1,
            },
            {
                key: "survivor-mining-discipline",
                archetypeKey: "wasteland-survivor",
                title: "Mining Discipline",
                description: "Represents steadier hands and planning in gathering work.",
                unlockLevel: 5,
                gridColumn: 2,
                gridRow: 1,
            },
            {
                key: "survivor-alchemy-basics",
                archetypeKey: "wasteland-survivor",
                title: "Alchemy Basics",
                description: "Opens the first layer of deeper fieldcraft and preparation.",
                unlockLevel: 10,
                prerequisites: [
                    "survivor-fishing-instinct",
                    "survivor-mining-discipline",
                ],
                gridColumn: 1,
                gridRow: 2,
            },
            {
                key: "survivor-double-trouble",
                archetypeKey: "wasteland-survivor",
                title: "Double Trouble",
                description: "A late branch for stacking practical wasteland utility.",
                unlockLevel: 15,
                prerequisites: ["survivor-alchemy-basics"],
                gridColumn: 1,
                gridRow: 3,
            },
        ],
    },
    {
        key: "combatant",
        label: "Combatant",
        description: "Combat readiness, movement, grit, and direct battlefield pressure.",
        nodes: [
            {
                key: "combatant-frog-legs",
                archetypeKey: "combatant",
                title: "Frog Legs",
                description: "Represents explosive movement, repositioning, and quick reactions.",
                unlockLevel: 5,
                gridColumn: 1,
                gridRow: 1,
            },
            {
                key: "combatant-iron-breath",
                archetypeKey: "combatant",
                title: "Iron Breath",
                description: "Builds stamina and composure for sustained combat pressure.",
                unlockLevel: 5,
                gridColumn: 2,
                gridRow: 1,
            },
            {
                key: "combatant-inner-force",
                archetypeKey: "combatant",
                title: "Inner Force",
                description: "A core node representing combat discipline and controlled aggression.",
                unlockLevel: 10,
                prerequisites: ["combatant-frog-legs", "combatant-iron-breath"],
                gridColumn: 1,
                gridRow: 2,
            },
            {
                key: "combatant-battle-trance",
                archetypeKey: "combatant",
                title: "Battle Trance",
                description: "The first deeper combat branch for high-pressure engagements.",
                unlockLevel: 15,
                prerequisites: ["combatant-inner-force"],
                gridColumn: 1,
                gridRow: 3,
            },
        ],
    },
];
