import herbImage from "../../../assets/items/resources/herb.png";
import ropeImage from "../../../assets/items/loot/rope.png";
import paperScrapImage from "../../../assets/items/resources/paperscrap.png";
import stoneImage from "../../../assets/items/resources/stone.png";
import woodImage from "../../../assets/items/resources/wood.png";
export const materialItemsData = [
    {
        key: "stone",
        name: "Stone",
        icon: stoneImage,
        iconKey: "stone",
        weight: 1.5,
        description: "A rough stone used for crafting and construction.",
        stats: ["Crafting material"],
        category: "material",
        stackable: true,
        baseValue: 1,
        tags: ["material", "construction"],
    },
    {
        key: "herb",
        name: "Herb",
        icon: herbImage,
        iconKey: "herb",
        weight: 0.2,
        description: "A medicinal herb with basic healing properties.",
        stats: ["Consumable ingredient"],
        category: "material",
        stackable: true,
        baseValue: 2,
        tags: ["material", "alchemy"],
    },
    {
        key: "wood",
        name: "Wood",
        icon: woodImage,
        iconKey: "wood",
        weight: 2,
        description: "Dry timber used for fuel, tools, and structures.",
        stats: ["Crafting material"],
        category: "material",
        stackable: true,
        baseValue: 1,
        tags: ["material", "construction"],
    },
    {
        key: "rope",
        name: "Rope",
        icon: ropeImage,
        iconKey: "rope",
        weight: 1,
        description: "Useful for climbing, binding, and field repairs.",
        stats: ["Traversal utility"],
        category: "material",
        stackable: true,
        baseValue: 4,
        tags: ["material", "utility", "traversal"],
    },
    {
        key: "paper",
        name: "Paper Scrap",
        icon: paperScrapImage,
        iconKey: "paper",
        weight: 0.1,
        description: "A fragile sheet salvaged from old records and books.",
        stats: ["Quest item material"],
        category: "quest",
        stackable: true,
        baseValue: 1,
        tags: ["quest", "lore", "material"],
    },
];
