import type { CreatureBestiaryData } from "./bestiaryTypes";

export const creatureCompendiumData: Record<string, CreatureBestiaryData> = {
  goblin: {
    key: "goblin",
    name: "Goblin",
    category: "humanoid",
    threatTier: "common",
    habitatTags: ["road", "ruins", "town"],
    isBossCandidate: false,
    maxHp: 18,
    maxSp: 6,
    drops: [
      { itemKey: "gold", label: "Gold Coins", rarity: "common", dropChancePercent: 100 },
      { itemKey: "rabbit-meat", label: "Rabbit Meat", rarity: "common", dropChancePercent: 100 },
      { itemKey: "rope", label: "Rope", rarity: "common", dropChancePercent: 70 },
      { itemKey: "pickaxe", label: "Pickaxe", rarity: "uncommon", dropChancePercent: 25 },
      { itemKey: "goblin-essence", label: "Goblin Essence", rarity: "rare", dropChancePercent: 1 },
      { itemKey: "goblin-helmet", label: "Goblin Helmet", rarity: "ultra-rare", dropChancePercent: 0.03 },
    ],
    weaknesses: ["Bleed", "Direct melee pressure"],
    resistances: ["Fear", "Harsh terrain"],
    strengths: ["Ambushes", "Quick retaliation"],
    attacks: [
      {
        key: "jagged-slash",
        label: "Jagged Slash",
        description: "A fast cut from a crude blade meant to punish hesitation.",
      },
      {
        key: "roadside-lunge",
        label: "Roadside Lunge",
        description: "A sudden leap meant to overwhelm isolated travelers.",
      },
    ],
    notes: [
      "Often found near roads and broken ruins.",
      "Aggressive when they believe they outnumber a target.",
    ],
  },
  orc: {
    key: "orc",
    name: "Orc",
    category: "humanoid",
    threatTier: "dangerous",
    habitatTags: ["forest", "road", "ruins"],
    isBossCandidate: false,
    maxHp: 42,
    maxSp: 14,
    drops: [
      { itemKey: "stone", label: "Stone", rarity: "common" },
      { itemKey: "wood", label: "Wood", rarity: "common" },
      { itemKey: "iron-ore", label: "Iron Ore", rarity: "rare" },
    ],
    weaknesses: ["Bleed", "Coordinated pressure"],
    resistances: ["Pain", "Intimidation"],
    strengths: ["Heavy blows", "Close-quarters aggression"],
    attacks: [
      {
        key: "cleaver-swing",
        label: "Cleaver Swing",
        description: "A brutal, wide swing meant to break a defender's footing.",
      },
    ],
    notes: ["Orcs favor direct confrontation and rough battlefield dominance."],
  },
  minotaur: {
    key: "minotaur",
    name: "Minotaur",
    category: "boss",
    threatTier: "elite",
    habitatTags: ["underground", "ruins"],
    isBossCandidate: true,
    maxHp: 96,
    maxSp: 20,
    drops: [
      { itemKey: "stone", label: "Stone", rarity: "common" },
      { itemKey: "rope", label: "Rope", rarity: "common" },
      { itemKey: "gold", label: "Ancient Gold", rarity: "rare" },
    ],
    weaknesses: ["Flanking", "Tight maneuvering traps"],
    resistances: ["Charge interruption", "Fear"],
    strengths: ["Rushdown", "Massive impact damage"],
    attacks: [
      {
        key: "labyrinth-charge",
        label: "Labyrinth Charge",
        description: "A devastating rush that overwhelms anything directly ahead.",
      },
    ],
    notes: ["Minotaurs are relentless once they commit to a pursuit line."],
  },
  dragon: {
    key: "dragon",
    name: "Dragon",
    category: "draconic",
    threatTier: "boss",
    habitatTags: ["ruins", "road"],
    isBossCandidate: true,
    maxHp: 260,
    maxSp: 80,
    drops: [
      { itemKey: "gold", label: "Gold", rarity: "common" },
      { itemKey: "stone", label: "Burnt Scale Fragment", rarity: "common" },
      { itemKey: "iron-ore", label: "Tempered Dragon Ore", rarity: "rare" },
    ],
    weaknesses: ["Prepared siege tactics", "Prolonged attrition"],
    resistances: ["Fire", "Fear", "Direct frontal assaults"],
    strengths: ["Area devastation", "Flight pressure", "Overwhelming durability"],
    attacks: [
      {
        key: "ember-breath",
        label: "Ember Breath",
        description: "A wave of searing flame that scorches everything in front of it.",
      },
      {
        key: "wing-shock",
        label: "Wing Shock",
        description: "A heavy wingbeat that throws enemies off balance.",
      },
    ],
    notes: ["Dragons should eventually be represented as boss-grade encounters."],
  },
  thief: {
    key: "thief",
    name: "Thief",
    category: "humanoid",
    threatTier: "common",
    habitatTags: ["town", "road", "ruins"],
    isBossCandidate: false,
    maxHp: 24,
    maxSp: 18,
    drops: [
      { itemKey: "rope", label: "Rope", rarity: "common" },
      { itemKey: "paper", label: "Stolen Note", rarity: "common" },
      { itemKey: "gold", label: "Hidden Coin Purse", rarity: "rare" },
    ],
    weaknesses: ["Vision control", "Direct pressure"],
    resistances: ["Ambush punishment", "Retreat routes"],
    strengths: ["Evasion", "Cheap strikes", "Loot theft"],
    attacks: [
      {
        key: "shiv-cut",
        label: "Shiv Cut",
        description: "A fast hit aimed at exposed gaps in a target's guard.",
      },
    ],
    notes: ["Thieves rely on positioning and opportunistic damage."],
  },
  yienkh: {
    key: "yienkh",
    name: "Yienkh",
    category: "aberration",
    threatTier: "dangerous",
    habitatTags: ["sewer", "swamp", "underground"],
    isBossCandidate: false,
    maxHp: 58,
    maxSp: 12,
    drops: [
      { itemKey: "rope", label: "Silk Thread", rarity: "common" },
      { itemKey: "herb", label: "Bog Herb", rarity: "common" },
      { itemKey: "paper", label: "Venom Notes", rarity: "rare" },
    ],
    weaknesses: ["Fire", "Sustained melee pressure"],
    resistances: ["Entrapment", "Poisoned terrain"],
    strengths: ["Web control", "Venom", "Ambush from above"],
    attacks: [
      {
        key: "web-snare",
        label: "Web Snare",
        description: "A sticky web cast that slows movement and creates openings.",
      },
      {
        key: "venom-bite",
        label: "Venom Bite",
        description: "A brutal bite that delivers lingering poison.",
      },
    ],
    notes: ["Yienkh is a giant spider species feared in swamps and ruined tunnels."],
  },
  ogre: {
    key: "ogre",
    name: "Ogre",
    category: "giant",
    threatTier: "elite",
    habitatTags: ["rural", "road", "ruins"],
    isBossCandidate: false,
    maxHp: 118,
    maxSp: 10,
    drops: [
      { itemKey: "wood", label: "Club Splinter", rarity: "common" },
      { itemKey: "stone", label: "Crushed Stone", rarity: "common" },
      { itemKey: "gold", label: "Smashed Tribute", rarity: "rare" },
    ],
    weaknesses: ["Mobility", "Repeated interrupts"],
    resistances: ["Stagger", "Minor wounds"],
    strengths: ["Raw impact", "Area knockback"],
    attacks: [
      {
        key: "maul-smash",
        label: "Maul Smash",
        description: "A crushing downward strike with terrible force.",
      },
    ],
    notes: ["Ogres are dangerous primarily because they endure and overpower."],
  },
  troll: {
    key: "troll",
    name: "Troll",
    category: "giant",
    threatTier: "elite",
    habitatTags: ["swamp", "forest", "underground"],
    isBossCandidate: false,
    maxHp: 134,
    maxSp: 16,
    drops: [
      { itemKey: "herb", label: "Bog Herb", rarity: "common" },
      { itemKey: "stone", label: "Swamp Stone", rarity: "common" },
      { itemKey: "rope", label: "Tough Tendon", rarity: "rare" },
    ],
    weaknesses: ["Fire", "Focused finishing pressure"],
    resistances: ["Attrition", "Minor cuts"],
    strengths: ["Regeneration", "Endurance", "Swamp fighting"],
    attacks: [
      {
        key: "rending-claw",
        label: "Rending Claw",
        description: "A tearing swipe meant to wear an enemy down over time.",
      },
    ],
    notes: ["Trolls should later support regeneration-specific combat logic."],
  },
};
